import { useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet } from 'react-native';
import Markdown from 'react-native-markdown-display';
import { SafeAreaView } from 'react-native-safe-area-context';

import { ThemedText } from '@/components/themed-text';
import { Colors, Radii, Spacing, Typography } from '@/constants/theme';

const TERMS_CONTENT = `# Terms of Service

_Last updated: 2026-04-20_

These Terms of Service ("Terms") govern your use of the Krashen mobile apps and website (the "Service"). The Service is operated by an individual sole proprietor ("autónomo") based in Spain. "Krashen" is a product name, not a registered legal entity. By creating an account or using the Service, you agree to these Terms. If you don't agree, please don't use the Service.

## The Service

Krashen is an interactive podcast player for language learners. You can listen to podcasts, tap words for instant explanation and translation, and ask voice or text questions about what you just heard. Answers are generated by AI and may contain inaccuracies.

## Your account

You must be at least **16 years old** to use the Service. You are responsible for keeping your login credentials secure and for activity under your account. Let us know at info@krashen.app if you suspect unauthorised use.

## Free trial and paid plans

Some features are available for free with a limited quota (for example, a capped number of questions). To continue using those features, you can subscribe to a paid plan via the App Store or Google Play. Subscription terms, pricing, and billing cycles are shown at checkout. Subscriptions renew automatically according to the store's rules unless cancelled before the renewal date. Cancellations are managed in your App Store or Google Play account.

## Acceptable use

You agree not to:

- Use the Service to break the law or infringe anyone's rights.
- Reverse-engineer, scrape, or attempt to extract the underlying models, transcripts, or infrastructure.
- Upload or submit content you don't have the right to share.
- Try to bypass quotas, paywalls, or authentication.
- Abuse, harass, or disrupt the Service or other users.

We may suspend or terminate accounts that violate these rules.

## Your content

When you ask a question, you grant us a licence to process your audio and text solely to provide the Service (transcription, answering, and service improvement). You retain ownership of your content. We do not store your audio recordings.

## AI-generated answers

Answers are generated by AI and are intended to help with language learning. They may be inaccurate, outdated, or incomplete. **Krashen is not a replacement for professional tutoring, translation, or expert advice.** Don't rely on the Service for critical decisions.

## Third-party content

Podcasts available in the Service are produced by third parties. We do not own or control their content, and we are not responsible for its accuracy or legality. Copyright for each podcast belongs to its respective owner.

## Service availability

We aim to keep the Service running reliably, but we do not guarantee uninterrupted access. We may update, change, or discontinue features at any time.

## Termination

You can stop using the Service and delete your account at any time. We may suspend or terminate your access if you breach these Terms or if required by law.

## Disclaimers

The Service is provided "as is" without warranties of any kind, express or implied, including warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not warrant that the Service will be error-free, secure, or that any specific learning outcome will be achieved.

## Limitation of liability

To the maximum extent permitted by law, Krashen is not liable for indirect, incidental, consequential, or punitive damages, or for lost profits, data, or goodwill. Our total liability for any claim related to the Service is limited to the amount you paid us in the 12 months before the claim, or USD 50 if you did not pay us anything.

Nothing in these Terms limits liability that cannot legally be excluded (including, for EU consumers, statutory rights).

## Changes to these Terms

We may update these Terms from time to time. Material changes will be communicated in the app or by email. Continued use of the Service after changes take effect means you accept the updated Terms.

## Governing law

These Terms are governed by the laws of **Spain**, without regard to conflict-of-law rules. Consumers in the EU, UK, and other jurisdictions retain the protection of the mandatory consumer-protection laws of their country of residence. Any disputes will be submitted to the competent courts of the operator's place of establishment in Spain, subject to any consumer rights that provide otherwise.

## Contact

Questions about these Terms: info@krashen.app.
`;

const markdownStyles = {
  body: {
    ...Typography.base,
  },
  heading1: {
    ...Typography.title,
    marginBottom: 16,
    marginTop: 8,
  },
  heading2: {
    ...Typography.subtitle,
    marginBottom: 12,
    marginTop: 20,
  },
  heading3: {
    color: Colors.cyan,
    fontSize: 16,
    fontWeight: '600' as const,
    marginBottom: 8,
    marginTop: 16,
  },
  strong: {
    color: Colors.textPrimary,
    fontWeight: '600' as const,
  },
  em: {
    color: Colors.cyan,
    fontStyle: 'italic' as const,
  },
  link: {
    color: Colors.cyan,
  },
  list_item: {
    color: Colors.textPrimary,
    fontSize: 15,
    lineHeight: 24,
  },
  bullet_list: {
    marginBottom: 8,
  },
  paragraph: {
    color: Colors.textPrimary,
    fontSize: 15,
    lineHeight: 24,
    marginBottom: 12,
  },
  code_inline: {
    backgroundColor: Colors.card,
    color: Colors.cyan,
    borderRadius: Radii.sm,
    paddingHorizontal: 4,
    paddingVertical: 2,
    fontSize: 14,
  },
};

export default function TermsScreen() {
  const router = useRouter();

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.content}
        showsVerticalScrollIndicator={false}
      >
        <Pressable onPress={() => router.back()}>
          <ThemedText type="link" style={styles.backLink}>
            ← Back
          </ThemedText>
        </Pressable>

        <Markdown style={markdownStyles}>{TERMS_CONTENT}</Markdown>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: Spacing.xl,
    paddingBottom: 40,
  },
  backLink: {
    marginTop: Spacing.md,
    marginBottom: Spacing.lg,
    fontSize: 14,
  },
});
